//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int ImageID { get; set; }
        public int ExamID { get; set; }
        public byte[] ImageRaw { get; set; }
    
        public virtual Exams Exams { get; set; }
    }
}
