//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppClinic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clinicvaultEntities : DbContext
    {
        public clinicvaultEntities()
            : base("name=clinicvaultEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exams> Exams { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Records> Records { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
    }
}
