//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int RecordID { get; set; }
        public string Token { get; set; }
        public string Pin1Token { get; set; }
        public string Pin2Token { get; set; }
    }
}
